// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF3NPoxi32nsAwkVY5uHIiDMZ9la-KrQM',
    appId: '1:944373114575:web:917a46ef2c6f794bfe79ba',
    messagingSenderId: '944373114575',
    projectId: 'aurafit-6dce7',
    authDomain: 'aurafit-6dce7.firebaseapp.com',
    storageBucket: 'aurafit-6dce7.firebasestorage.app',
    measurementId: 'G-XDC8JZ9E37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI6alttvp76JYBhv1pOKYSusn1scsaDHs',
    appId: '1:944373114575:android:a9fb68af91b65336fe79ba',
    messagingSenderId: '944373114575',
    projectId: 'aurafit-6dce7',
    storageBucket: 'aurafit-6dce7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnw5_teab5ioQTMFJ4dZlQN8mnojt8PXU',
    appId: '1:944373114575:ios:0fcc3ea9d47aaf4efe79ba',
    messagingSenderId: '944373114575',
    projectId: 'aurafit-6dce7',
    storageBucket: 'aurafit-6dce7.firebasestorage.app',
    iosBundleId: 'kz.konina.aurafit_ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnw5_teab5ioQTMFJ4dZlQN8mnojt8PXU',
    appId: '1:944373114575:ios:0fcc3ea9d47aaf4efe79ba',
    messagingSenderId: '944373114575',
    projectId: 'aurafit-6dce7',
    storageBucket: 'aurafit-6dce7.firebasestorage.app',
    iosBundleId: 'kz.konina.aurafit_ai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF3NPoxi32nsAwkVY5uHIiDMZ9la-KrQM',
    appId: '1:944373114575:web:b22fb5d14741557bfe79ba',
    messagingSenderId: '944373114575',
    projectId: 'aurafit-6dce7',
    authDomain: 'aurafit-6dce7.firebaseapp.com',
    storageBucket: 'aurafit-6dce7.firebasestorage.app',
    measurementId: 'G-TSFSBSNTYN',
  );
}
