// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5H3vgOULJ5kbDn2hurusMD5YHU-c9-gE',
    appId: '1:153749492357:web:cba0616af6226c317b0fec',
    messagingSenderId: '153749492357',
    projectId: 'aurafit-dbd9b',
    authDomain: 'aurafit-dbd9b.firebaseapp.com',
    storageBucket: 'aurafit-dbd9b.firebasestorage.app',
    measurementId: 'G-4J5PN2NLPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFv9tP24AANf9lFsIhEQGCYrJw0HYneNU',
    appId: '1:153749492357:android:abe8ef81636e612d7b0fec',
    messagingSenderId: '153749492357',
    projectId: 'aurafit-dbd9b',
    storageBucket: 'aurafit-dbd9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwRasX2GXm0ikcikXAkUSpRIcLiV_vHeo',
    appId: '1:153749492357:ios:50f58c947d7662e67b0fec',
    messagingSenderId: '153749492357',
    projectId: 'aurafit-dbd9b',
    storageBucket: 'aurafit-dbd9b.firebasestorage.app',
    iosBundleId: 'com.example.aurafitAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwRasX2GXm0ikcikXAkUSpRIcLiV_vHeo',
    appId: '1:153749492357:ios:50f58c947d7662e67b0fec',
    messagingSenderId: '153749492357',
    projectId: 'aurafit-dbd9b',
    storageBucket: 'aurafit-dbd9b.firebasestorage.app',
    iosBundleId: 'com.example.aurafitAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5H3vgOULJ5kbDn2hurusMD5YHU-c9-gE',
    appId: '1:153749492357:web:6ffba79c3ef0da447b0fec',
    messagingSenderId: '153749492357',
    projectId: 'aurafit-dbd9b',
    authDomain: 'aurafit-dbd9b.firebaseapp.com',
    storageBucket: 'aurafit-dbd9b.firebasestorage.app',
    measurementId: 'G-03Q7M0T5M2',
  );

}