import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../services/ai_service.dart';

class ScheduleScreen extends StatefulWidget {
  const ScheduleScreen({super.key});

  @override
  State<ScheduleScreen> createState() => _ScheduleScreenState();
}

class _ScheduleScreenState extends State<ScheduleScreen> {
  late Future<String> _schedule;

  @override
  void initState() {
    super.initState();
    _schedule = _loadSchedule();
  }

  Future<String> _loadSchedule() async {
    final prefs = await SharedPreferences.getInstance();
    final weight = prefs.getString('user_weight') ?? '70';
    final height = prefs.getString('user_height') ?? '175';

    final response = await AiService.generateSchedule(weight: weight, height: height);
    return response.replaceAll('*', '').trim();
  }

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;

    return Scaffold(
      appBar: AppBar(
        title: const Text('AI Daily Schedule'),
      ),
      body: FutureBuilder<String>(
        future: _schedule,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return Center(
              child: CircularProgressIndicator(color: scheme.primary),
            );
          }

          if (snapshot.hasError) {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.error_outline, color: scheme.error, size: 40),
                  const SizedBox(height: 10),
                  const Text('Не удалось загрузить расписание'),
                  TextButton(
                    onPressed: () => setState(() => _schedule = _loadSchedule()),
                    child: const Text('Повторить'),
                  )
                ],
              ),
            );
          }

          return SingleChildScrollView(
            padding: const EdgeInsets.all(20),
            child: Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: scheme.surfaceContainerHighest.withValues(alpha: 0.65),
                borderRadius: BorderRadius.circular(20),
                border: Border.all(color: scheme.outline.withValues(alpha: 0.35)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Icon(Icons.auto_awesome, color: scheme.primary, size: 20),
                      const SizedBox(width: 10),
                      Text(
                        'Generated by AuraFit AI',
                        style: TextStyle(
                          color: scheme.primary,
                          fontSize: 12,
                          fontWeight: FontWeight.bold,
                          letterSpacing: 1.1,
                        ),
                      ),
                    ],
                  ),
                  Divider(height: 30, color: scheme.outline.withValues(alpha: 0.3)),
                  Text(
                    snapshot.data ?? '',
                    style: Theme.of(context).textTheme.bodyLarge?.copyWith(height: 1.6),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}
