import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../services/ai_service.dart';

class ScheduleScreen extends StatefulWidget {
  const ScheduleScreen({super.key});

  @override
  State<ScheduleScreen> createState() => _ScheduleScreenState();
}

class _ScheduleScreenState extends State<ScheduleScreen> {
  late Future<String> _schedule;

  @override
  void initState() {
    super.initState();
    _schedule = _loadSchedule();
  }

  Future<String> _loadSchedule() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final weight = prefs.getString('user_weight') ?? "70";
      final height = prefs.getString('user_height') ?? "175";
      
      final response = await AiService.generateSchedule(weight: weight, height: height);
      
      // Небольшая очистка текста от лишних Markdown-символов для красоты
      return response.replaceAll('*', '').trim();
    } catch (e) {
      throw Exception("Failed to load schedule");
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0F0F13),
      appBar: AppBar(
        title: const Text("AI Daily Schedule", style: TextStyle(fontWeight: FontWeight.bold)),
        backgroundColor: Colors.transparent,
        elevation: 0,
        centerTitle: true,
      ),
      body: FutureBuilder<String>(
        future: _schedule,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(
              child: CircularProgressIndicator(color: Colors.deepPurpleAccent),
            );
          } else if (snapshot.hasError) {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.error_outline, color: Colors.redAccent, size: 40),
                  const SizedBox(height: 10),
                  const Text("Не удалось загрузить расписание", style: TextStyle(color: Colors.white70)),
                  TextButton(
                    onPressed: () => setState(() => _schedule = _loadSchedule()),
                    child: const Text("Повторить", style: TextStyle(color: Colors.deepPurpleAccent)),
                  )
                ],
              ),
            );
          }

          return SingleChildScrollView(
            padding: const EdgeInsets.all(20),
            child: Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                // ИСПРАВЛЕНО: .withValues вместо .withOpacity
                color: Colors.white.withValues(alpha: 0.05),
                borderRadius: BorderRadius.circular(20),
                border: Border.all(color: Colors.white.withValues(alpha: 0.1)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      const Icon(Icons.auto_awesome, color: Colors.deepPurpleAccent, size: 20),
                      const SizedBox(width: 10),
                      Text(
                        "Generated by AuraFit AI",
                        style: TextStyle(
                          color: Colors.deepPurpleAccent.withValues(alpha: 0.8),
                          fontSize: 12,
                          fontWeight: FontWeight.bold,
                          letterSpacing: 1.1,
                        ),
                      ),
                    ],
                  ),
                  const Divider(height: 30, color: Colors.white10),
                  Text(
                    snapshot.data ?? "",
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      height: 1.6, // 
                    ),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}